### ISSUE TITLE
Received an error when starting.

### ISSUE THREAD

**Issue by dshitik** [meddlin/thekove#19]
Error: Match error: Expected string, got undefined in field email
W20170402-02:20:04.820(3)? (STDERR)     at exports.check (packages/check.js:57:15)
W20170402-02:20:04.821(3)? (STDERR)     at createUser (packages/accounts-password/password_server.js:983:3)
W20170402-02:20:04.822(3)? (STDERR)     at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1078:10)
W20170402-02:20:04.823(3)? (STDERR)     at server/main.js:15:33
W20170402-02:20:04.823(3)? (STDERR)     at Function.time (/home/dmitry/Meteor App/thekove/.meteor/local/build/programs/server/profile.js:309:28)
W20170402-02:20:04.824(3)? (STDERR)     at /home/dmitry/Meteor App/thekove/.meteor/local/build/programs/server/boot.js:312:13
W20170402-02:20:04.826(3)? (STDERR)     at /home/dmitry/Meteor App/thekove/.meteor/local/build/programs/server/boot.js:353:5
W20170402-02:20:04.827(3)? (STDERR)     at Function.run (/home/dmitry/Meteor App/thekove/.meteor/local/build/programs/server/profile.js:510:12)
W20170402-02:20:04.827(3)? (STDERR)     at /home/dmitry/Meteor App/thekove/.meteor/local/build/programs/server/boot.js:351:11

**Comment by meddlin** [comment]
This is more than likely associated with the settings file. I'll address it as soon as I can.

**Comment by meddlin** [comment]
In server/main.js it's assumed the defaultUser is set in the environment variables. So, without a settings file on initial startup the project will fail.

It doesn't appear to be enough to start the project with: "meteor --settings settings-dev.json"

server/main.js
```javascript
if (Meteor.users.find().count() == 0) {
  	let defaultUserId = Accounts.createUser({
  		/*email: "admin@admin.com",
  		password: "password"*/
  		email: process.env.DEFAULT_USER_EMAIL,
  		password: process.env.DEFAULT_USER_PASSWORD
  	});
  	return Roles.addUsersToRoles(defaultUserId, 'admin');
  }
```

**Comment by meddlin** [comment]
Resolved https://github.com/meddlin/thekove/commit/8729b95210ce848fc3fe76d8526a6a89553ea1d1
